GET http://localhost:5000/comment

###
POST http://localhost:5000/comment
Content-Type: application/json

{
  "forum": "647a2b9a37fd75e865a2af02",
  "commentContent": "Wow that looks so delicious! Please hand me the Recipes 🥩"
}


###
DELETE http://localhost:5000/comment/647a2c9727eb783e30dff383